# Generated by Django 5.2.5 on 2025-09-18 10:09

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(help_text='Enter a 10-digit mobile number', max_length=10, validators=[student.models.mobile_number_len]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.PositiveIntegerField(help_text='Enter 6-digit Pin Code', validators=[student.models.validate_pin_length]),
        ),
    ]
