# Generated by Django 5.2.5 on 2025-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
